// Aspect class mapping - based on the Discord bot's aspect_class_map.json
export const aspectClassMap: { [className: string]: string[] } = {
  "mage": [
    "Aspect of the Apprentice's Bolt",
    "Aspect of the Comet",
    "Aspect of the Cone of Cold",
    "Aspect of the Dimension's Door",
    "Aspect of the Magic Missile",
    "Aspect of the Ray of Frost",
    "Aspect of the Savior",
    "Aspect of a Scorching Sun",
    "Aspect of a Thousand Hours",
    "Aspect of Wind Walking",
    "Aspect of Burning Providence",
    "Aspect of Fatal Fulguration",
    "Aspect of Flickering Transmission",
    "Aspect of Mystic Transfer",
    "Aspect of Runic Extravagance",
    "Aspect of Shining Status",
    "Riftwalker's Embodiment of Chronal Control",
    "Light Bender's Embodiment of Celestial Brilliance",
    "Arcanist's Embodiment of Total Obliteration"
  ],
  "archer": [
    "Aspect of Battlement Fortification",
    "Aspect of Bullet Hell",
    "Aspect of Clinging Lichen",
    "Aspect of Dynamic Entry",
    "Aspect of Extreme Firepower",
    "Aspect of Further Horizons",
    "Aspect of Illegal Explosives",
    "Aspect of the North Wind",
    "Aspect of Chaotic Demolition",
    "Aspect of Extreme Current",
    "Aspect of Fragmentation Rounds",
    "Aspect of the Great Escape",
    "Aspect of the Inexhaustible Quiver",
    "Aspect of the Poltergeist",
    "Aspect of a Thunderbolt",
    "Aspect of Undercrank",
    "Aspect of the Beastmaster",
    "Boltslinger's Embodiment of Rended Skies",
    "Trapper's Embodiment of Persistence Predation",
    "Sharpshooter's Embodiment of Laser Precision"
  ],
  "warrior": [
    "Aspect of the Anvil Drop",
    "Aspect of Bovine Inspiration",
    "Aspect of Building Rage",
    "Aspect of a Crashing Wake",
    "Aspect of the Death Blow",
    "Aspect of a Falling Anvil",
    "Aspect of the Flying Kick",
    "Aspect of a Heroic Charge",
    "Aspect of Iron Will",
    "Aspect of the Last Resort",
    "Aspect of Provocation",
    "Aspect of the Sky's Cry",
    "Aspect of the Swinging Sword",
    "Aspect of the Titan",
    "Aspect of a War Cry",
    "Aspect of the Weaponmaster",
    "Aspect of the Weighted Weapon",
    "Aspect of a Whirling Blade",
    "Fallen's Embodiment of Crushing Weight",
    "Paladin's Embodiment of Valor's Call",
    "Berserker's Embodiment of Undying Fury"
  ],
  "assassin": [
    "Aspect of the Acrobat",
    "Aspect of a Backstab",
    "Aspect of Blade Fury",
    "Aspect of the Blade Storm",
    "Aspect of Blinding Smoke",
    "Aspect of the Bloodhound",
    "Aspect of the Crowstorm",
    "Aspect of the Dead Walker",
    "Aspect of the Lacerator",
    "Aspect of the Last Laugh",
    "Aspect of Lethal Defense",
    "Aspect of Marked Target",
    "Aspect of Multihit",
    "Aspect of the Puppeteer",
    "Aspect of a Quick Slash",
    "Aspect of Smoke Bombing",
    "Aspect of the Spear of Vanishing",
    "Aspect of Spinning Assassin",
    "Aspect of Unforeseen Assasination",
    "Aspect of Vanish",
    "Trickster's Embodiment of Spine-Chilling Terror",
    "Acrobat's Embodiment of Speed and Grace",
    "Assassin's Embodiment of Lethal Precision"
  ],
  "shaman": [
    "Aspect of the Aura",
    "Aspect of Crimson Lightning",
    "Aspect of the Cursed",
    "Aspect of the Decaying Swarm",
    "Aspect of Dexterity",
    "Aspect of Epidemic",
    "Aspect of the Genesis",
    "Aspect of Healing",
    "Aspect of the Horde",
    "Aspect of the Lightning Serpent",
    "Aspect of the Mask",
    "Aspect of the Plague Bomb",
    "Aspect of the Rain's Blessing",
    "Aspect of Relay",
    "Aspect of the Scarred Earth",
    "Aspect of Spirit Walk",
    "Aspect of the Storm",
    "Aspect of Totem Overload",
    "Ritualist's Embodiment of Bitter Poison",
    "Summoner's Embodiment of Overwhelming Swarm",
    "Acolyte's Embodiment of Undying Spirit"
  ]
};

export const getClassForAspect = (aspectName: string): string | null => {
  for (const [className, aspects] of Object.entries(aspectClassMap)) {
    if (aspects.includes(aspectName)) {
      return className;
    }
  }
  return null;
};
