/**
 * Territory name abbreviations for compact storage in history snapshots.
 * Each territory has a unique 2-4 character code.
 */

// Full name → Abbreviation mapping
export const TERRITORY_TO_ABBREV: Record<string, string> = {
  // A
  "Abandoned Farm": "ABF",
  "Abandoned Lumberyard": "ABL",
  "Abandoned Mines": "ABM",
  "Abandoned Mines Entrance": "AME",
  "Abandoned Pass": "ABP",
  "Accursed Dunes": "ACD",
  "Aerial Descent": "ARD",
  "Agricultural Sector": "AGS",
  "Ahmsord": "AHM",
  "Ahmsord Outskirts": "AHO",
  "Akias Ruins": "AKR",
  "Alder Understory": "ALU",
  "Aldorei Cliffside Waterfalls": "ACW",
  "Aldorei River": "ALR",
  "Aldorei Springs": "ALS",
  "Aldorei Valley": "ALV",
  "Aldorei Valley Outskirts": "AVO",
  "Aldwell": "ALD",
  "Alekin": "ALK",
  "Almuj": "ALM",
  "Almuj Slums": "AMS",
  "Ancient Excavation": "AEX",
  "Ancient Nemract": "ANM",
  "Ancient Waterworks": "AWW",
  "Angel Refuge": "ARF",
  "Apprentice Huts": "APH",
  "Arachnid Woods": "ARW",
  "Astraulus' Tower": "AST",
  "Ava's Workshop": "AVW",
  "Avos Temple": "AVT",
  "Avos Territory": "AVY",
  "Azure Frontier": "AZF",

  // B
  "Balloon Airbase": "BAB",
  "Bandit Cave": "BCV",
  "Bandit's Toll": "BTL",
  "Bantisu Air Temple": "BAT",
  "Bantisu Approach": "BTA",
  "Barren Sands": "BRS",
  "Bear Zoo": "BRZ",
  "Big Mushroom Cave": "BMC",
  "Bizarre Passage": "BZP",
  "Black Road": "BLR",
  "Blackstring Den": "BSD",
  "Bloody Beach": "BBH",
  "Bloody Trail": "BTR",
  "Blooming Boulders": "BLB",
  "Bob's Tomb": "BOB",
  "Bremminglar": "BRM",
  "Brigand Outpost": "BOP",
  "Broken Road": "BKR",
  "Bucie Waterfall": "BCW",
  "Burning Airship": "BAS",
  "Burning Farm": "BFM",

  // C
  "Canyon Dropoff": "CDO",
  "Canyon High Path": "CHP",
  "Canyon Walkway": "CWY",
  "Citadel's Shadow": "CTS",
  "Contested District": "CTD",
  "Caritat Mansion": "CRM",
  "Cascading Basins": "CSB",
  "Cascading Oasis": "CSO",
  "Castle Dullahan": "CDH",
  "Cathedral Harbour": "CTH",
  "Celestial Impact": "CLI",
  "Centerworld Fortress": "CWF",
  "Central Islands": "CTI",
  "Chasm Chokepoint": "CCH",
  "Chasm Overlook": "CHO",
  "Cherry Blossom Grove": "CBG",
  "Cinfras": "CIN",
  "Cinfras Outskirts": "CIO",
  "Cinfras's Small Farm": "CSF",
  "Cliffhearth Orc Camp": "COC",
  "Cliffside Passage North": "CPN",
  "Cliffside Passage South": "CPS",
  "Coastal Trail": "CTL",
  "Collapsed Bridge": "CLB",
  "Collapsed Emerald Mine": "CEM",
  "Colourful Mountaintop": "CMT",
  "Corkus Castle": "CKC",
  "Corkus City": "CC",
  "Corkus City Crossroads": "CCC",
  "Corkus City Mine": "CCM",
  "Corkus Forest": "CKF",
  "Corkus Outskirts": "CKO",
  "Corkus Sea Cove": "CSC",
  "Corrupted Orchard": "CRO",
  "Corrupted River": "CRR",
  "Corrupted Road": "CRD",
  "Corrupted Tower": "CRT",
  "Corrupted Warfront": "CWR",
  "Cosmic Fissures": "CMF",
  "Crater Descent": "CRD2",
  "Cyclospordial Hazard": "CYH",

  // D
  "Deforested Ecotone": "DFE",
  "Dark Forest Village": "DFV",
  "Decayed Basin": "DCB",
  "Delnar Manor": "DLM",
  "Derelict Mansion": "DRM",
  "Desolate Valley": "DSV",
  "Detlas": "DET",
  "Detlas Suburbs": "DTS",
  "Displaced Housing": "DPH",
  "Disturbed Crypt": "DBC",
  "Dodegar's Forge": "DGF",
  "Dogun Ritual Site": "DRS",
  "Dragonbone Graveyard": "DBG",
  "Dragonling Nests": "DLN",
  "Dreary Docks": "DRD",
  "Dujgon Nation": "DJN",
  "Durum Barley Islet": "DBI",
  "Durum Isles Barn": "DIB",
  "Durum Malt Islet": "DMI",
  "Durum Oat Islet": "DOI",
  "Dusty Pit": "DPT",

  // E
  "Eagle Tribe": "EGT",
  "Efilim": "EFL",
  "Efilim Crossroads": "EFC",
  "Elefolk Stomping Grounds": "ESG",
  "Elephelk Trail": "ELT",
  "Elkurn": "ELK",
  "Eltom": "ELM",
  "Emerald Trail": "EMT",
  "Enchanted River": "ECR",
  "Entamis Village": "ENV",
  "Entrance to Almuj": "ETA",
  "Entrance to Bucie": "ETB",
  "Entrance to Cinfras": "ETC",
  "Entrance to Gavel": "ETG",
  "Entrance to Kander": "ETK",
  "Entrance to Molten Heights": "EMH",
  "Entrance to Nivla Woods": "ENW",
  "Espren": "EPR",
  "Entrance to Olux": "ETO",
  "Entrance to Thesead": "ETT",
  "Essren's Hut": "ESH",
  "Evergreen Outbreak": "EGO",

  // F
  "Fading Forest": "FDF",
  "Fallen Factory": "FFY",
  "Fallen Village": "FVL",
  "Faltach Manor": "FTM",
  "Farmers Settlement": "FMS",
  "Featherfall Cliffs": "FFC",
  "Felroc Fields": "FRF",
  "Festival Grounds": "FGD",
  "Feuding Houses": "FDH",
  "Field of Life": "FOL",
  "Final Step": "FNS",
  "Fleris Cranny": "FLC",
  "Fleris Trail": "FLT",
  "Floral Peaks": "FLP",
  "Florist's Hut": "FLH",
  "Forest of Eyes": "FOE",
  "Fort Hegea": "FHG",
  "Fort Tericen": "FTC",
  "Fort Torann": "FTR",
  "Forts in Fall": "FIF",
  "Forgotten Burrows": "FGB",
  "Forgotten Path": "FGP",
  "Forgotten Town": "FGT",
  "Founder's Statue": "FDS",
  "Fountain of Youth": "FOY",
  "Freezing Heights": "FZH",
  "Frigid Crossroads": "FCR",
  "Frosty Outpost": "FSO",
  "Frosty Spikes": "FSP",
  "Frozen Fort": "FFT",
  "Frozen Homestead": "FHS",
  "Fungal Grove": "FNG",

  // G
  "Gates to Aelumia": "GTA",
  "Gateway to Nothing": "GTN",
  "Gelibord": "GLB",
  "Gelibord Watermill": "GWM",
  "Gert Camp": "GTC",
  "Gloopy Cave": "GLC",
  "Goblin Plains East": "GPE",
  "Goblin Plains West": "GPW",
  "Great Bridge": "GBR",
  "Grey Ruins": "GRR",
  "Guardian of the Forest": "GOF",
  "Guild Hall": "GHL",
  "Gylia Fisherman Camp": "GFC",
  "Gylia Lakehouse": "GLH",
  "Gylia Research Cabin": "GRC",
  "Gylia Watchtower": "GWT",

  // H
  "Half Moon Island": "HMI",
  "Highlands Gate": "HLG",
  "Harnort Compound": "HNC",
  "Harpy's Haunt North": "HHN",
  "Harpy's Haunt South": "HHS",
  "Heart of Decay": "HOD",
  "Heavenly Ingress": "HVI",
  "Herb Cave": "HBC",
  "Hobgoblin's Hoard": "HGH",
  "Housing Crisis": "HCR",
  "Hyloch": "HYL",

  // I
  "Iboju Village": "IBV",
  "Icy Descent": "ICD",
  "Icy Island": "ICY",
  "Icy Vigil": "ICV",
  "Illuminant Path": "ILP",
  "Industrial Clearing": "INC",
  "Industrial Sector": "INS",
  "Infested Sinkhole": "ISH",
  "Inhospitable Mountain": "IHM",
  "Invaded Barracks": "INB",
  "Iron Road": "IRR",

  // J
  "Jagged Foothills": "JGF",
  "Jitak's Farm": "JTF",
  "Jofash Docks": "JFD",
  "Jofash Tunnel": "JFT",
  "Jungle Entrance": "JNE",

  // K
  "Kander Mines": "KDM",
  "Kandon Farm": "KNF",
  "Kandon Ridge": "KNR",
  "Kandon-Beda": "KNB",
  "Karoc Quarry": "KRQ",
  "Katoa Ranch": "KTR",
  "Kitrios Armory": "KTA",
  "Kitrios Barracks": "KTB",
  "Krolton's Cave": "KRC",

  // L
  "Lake Gitephe": "LGT",
  "Lake Rieke": "LRK",
  "Lava Lakes": "LVL",
  "Lava Springs": "LVS",
  "Legendary Island": "LGI",
  "Lexdale": "LXD",
  "Lexdale Penitentiary": "LXP",
  "Lifeless Forest": "LLF",
  "Light Peninsula": "LPN",
  "Lighthouse Lookout": "LHL",
  "Lion Lair": "LNL",
  "Little Wood": "LTW",
  "Lizardman Camp": "LZC",
  "Lizardman Lake": "LZL",
  "Llevigar": "LLV",
  "Llevigar Farm": "LVF",
  "Llevigar Gate": "LVG",
  "Llevigar Stables": "LVB",
  "Loamsprout Orc Camp": "LOC",
  "Lost Atoll": "LAT",
  "Luminous Plateau": "LMP",
  "Lusuco": "LSC",
  "Lutho": "LTH",
  "Luxuriant Pond": "LXP2",

  // M
  "Mage Island": "MGI",
  "Maiden Tower": "MDT",
  "Maltic": "MLT",
  "Maltic Coast": "MLC",
  "Mangled Lake": "MGL",
  "Mantis Nest": "MNT",
  "Maro Peaks": "MRP",
  "Mesquis Tower": "MST",
  "Meteor Crater": "MTC",
  "Meteor Trail": "MTR",
  "Mine Base Plains": "MBP",
  "Mining Base Camp": "MBC",
  "Minotaur Barbecue": "MNB",
  "Molten Passage": "MPS",
  "Molten Reach": "MLR",
  "Monte's Village": "MTV",
  "Mount Wynn Inn": "MWI",
  "Mudspring Orc Camp": "MOC",
  "Mummy's Tomb": "MMT",
  "Mushroom Hill": "MSH",
  "Mycelial Expanse": "MYE",
  "Myconid Descent": "MYD",

  // N
  "Naga Lake": "NGL",
  "Nemract": "NMR",
  "Nemract Cathedral": "NMC",
  "Nesaak": "NSK",
  "Nesaak Transition": "NST",
  "Nested Cliffside": "NCS",
  "Nexus of Light": "NOL",
  "Nivla Woods": "NVW",
  "Nivla Woods Exit": "NWE",
  "Nodguj Nation": "NDN",
  "Nomads' Refuge": "NRF",

  // O
  "Ogre Den": "OGD",
  "Old Coal Mine": "OCM",
  "Old Crossroads": "OCR",
  "Olux": "OLX",
  "Olux Lumberyard": "OLY",
  "Orc Battlegrounds": "OBG",
  "Orc Lake": "ORL",
  "Orc Road": "ORR",
  "Otherworldly Monolith": "OWM",
  "Outer Aldorei Town": "OAT",
  "Overrun Docks": "OVD",
  "Overtaken Outpost": "OTO",
  "Owl Tribe": "OWT",

  // P
  "Panda Kingdom": "PDK",
  "Panda Path": "PDP",
  "Paper Trail": "PPT",
  "Parasitic Slime Mine": "PSM",
  "Path to Ahmsord": "PTA",
  "Path to Cinfras": "PTC",
  "Path to Light": "PTL",
  "Path to Light's Secret": "PLS",
  "Path to Ozoth's Spire": "POS",
  "Path to Talor": "PTT",
  "Path to Thanos": "PTH",
  "Path to the Dojo": "PTD",
  "Path to the Forgery": "PTF",
  "Path to the Grootslangs": "PTG",
  "Path to the Penitentiary": "PTP",
  "Paths of Sludge": "POS2",
  "Perilous Grotto": "PGT",
  "Perilous Passage": "PPG",
  "Picnic Pond": "PCP",
  "Pigmen Ravines": "PMR",
  "Pine Pillar Forest": "PPF",
  "Pirate Town": "PRT",
  "Plains Lake": "PLK",
  "Primal Fen": "PMF",
  "Protector's Pathway": "PRW",
  "Pyroclastic Flow": "PCF",

  // R
  "Residence Sector": "RSD",
  "Ragni": "RAG",
  "Ragni Countryside North": "RCN",
  "Ragni Countryside South": "RCS",
  "Ragni Main Entrance": "RME",
  "Ragni North Entrance": "RNE",
  "Ragni South Entrance": "RSE",
  "Raiders' Airbase": "RAB",
  "Raiders' Stronghold": "RSH",
  "Ranol's Farm": "RNF",
  "Razed Inn": "RZI",
  "Regular Island": "RGI",
  "Relos": "RLS",
  "Retrofitted Manufactory": "RTM",
  "Riverbank Knoll": "RBK",
  "Road to Elkurn": "RTE",
  "Road to Light Forest": "RLF",
  "Road to Mine": "RTM2",
  "Road to Time Valley": "RTV",
  "Rocky Bend": "RKB",
  "Rocky Shore": "RKS",
  "Rodoroc": "RDR",
  "Rooster Island": "RSI",
  "Roots of Corruption": "ROC",
  "Royal Barracks": "RYB",
  "Royal Dam": "RYD",
  "Royal Gate": "RYG",
  "Ruined Houses": "RNH",
  "Ruined Prospect": "RNP",
  "Ruined Villa": "RNV",
  "Rymek": "RYM",

  // S
  "Sablestone Orc Camp": "SOC",
  "Sanctuary Bridge": "SCB",
  "Sanguine Spider Den": "SSD",
  "Santa's Hideout": "STH",
  "Savannah Plains": "SVP",
  "Scorched Trail": "SCT",
  "Scorpion Nest": "SPN",
  "Secluded Ponds": "SCP",
  "Secluded Workshop": "SCW",
  "Selchar": "SEL",
  "Shady Shack": "SDS",
  "Shineridge Orc Camp": "SRC",
  "Silent Road": "SLR",
  "Silverbull Headquarters": "SBH",
  "Sinister Forest": "SNF",
  "Skien's Island": "SKI",
  "Sky Castle": "SKC",
  "Sky Falls": "SKF",
  "Sky Island Ascent": "SIA",
  "Snail Island": "SNI",
  "Southern Outpost": "SOP",
  "Stonecave Orc Camp": "STC",
  "Sulphuric Hollow": "SPH",
  "Sunrise Plateau": "SRP",
  "Sunset Plateau": "SNP",
  "Sunspark Orc Camp": "SSO",
  "Swamp Island": "SWI",
  "Swamp Mountain Arch": "SMA",

  // T
  "Talor Cemetery": "TLC",
  "Temple Island": "TPI",
  "Temple of Legends": "TOL",
  "Tempo Town": "TMT",
  "Ternaves": "TRN",
  "Ternaves Tunnel": "TRT",
  "Thanos": "THA",
  "Thanos Exit": "THE",
  "Thanos Underpass": "THU",
  "The Forgery": "TFG",
  "The Frog Bog": "TFB",
  "The Gate": "TGT",
  "The Hive": "THV",
  "The Lumbermill": "TLM",
  "The Shiar": "TSH",
  "Thesead": "TSD",
  "Thesead Suburbs": "TSS",
  "Thesead Underpass": "TSU",
  "Timasca": "TMS",
  "Time Valley": "TMV",
  "Timeworn Arch": "TWA",
  "Tower of Ascension": "TOA",
  "Toxic Caves": "TXC",
  "Toxic Drip": "TXD",
  "Tree Island": "TRI",
  "Troll Tower": "TLT",
  "Troll's Challenge": "TRC",
  "Troms": "TRM",
  "Troms Lake": "TRL",
  "Trunkstump Goblin Camp": "TGC",
  "Turncoat Turnabout": "TCT",
  "Twain Lake": "TWL",
  "Twain Mansion": "TWM",
  "Twisted Housing": "TWH",
  "Twisted Ridge": "TWR",

  // U
  "Unicorn Trail": "UNT",
  "University Campus": "UNC",
  "Upper Thanos": "UTH",

  // V
  "Verdant Grove": "VDG",
  "Viscera Pits": "VCP",
  "Void Valley": "VDV",
  "Volcanic Excavation": "VLE",
  "Volcanic Isles": "VLI",

  // W
  "Wanderer's Way": "WDW",
  "Water Processing Sector": "WPS",
  "Waterfall Cave": "WFC",
  "Wayward Split": "WWS",
  "Webbed Fracture": "WBF",
  "Weird Clearing": "WRC",
  "Wellspring of Eternity": "WOE",
  "Winding Waters": "WWW",
  "Witching Road": "WTR",
  "Wizard Tower": "WZT",
  "Wizard's Warning": "WZW",
  "Wolves' Den": "WLD",
  "Wood Sprite Hideaway": "WSH",
  "Workshop Glade": "WKG",
  "Worm Tunnel": "WMT",
  "Wybel Island": "WBI",

  // X
  "Xima Valley": "XMV",

  // Z
  "Zhight Island": "ZHI",
};

// Cutoff: territories below only existed before the Rekindled World update.
// The 2.1 Rekindled World update went live on August 10, 2024.
export const REKINDLED_WORLD_CUTOFF_MS = new Date("2024-08-10T00:00:00Z").getTime();

// Old territory names that were REMOVED in the 2.1 Rekindled World update.
// These should not appear on the map for timestamps after REKINDLED_WORLD_CUTOFF_MS.
const OLD_TERRITORY_TO_ABBREV: Record<string, string> = {
  "Abandoned Manor": "AMA",
  "Active Volcano": "ACV",
  "Air Temple Lower": "ATL",
  "Air Temple Upper": "ATU",
  "Aldorei Lowlands": "ALL",
  "Aldorei Valley Lower": "AVL",
  "Aldorei Valley Mid": "AVM",
  "Aldorei Valley Upper": "AVU",
  "Aldorei Valley West Entrance": "AVWE",
  "Aldorei\u2019s North Exit": "ANE",
  "Aldorei\u2019s River": "ARI",
  "Aldorei\u2019s Waterfall": "ALW",
  "Almuj City": "ALC",
  "Arachnid Route": "ARR",
  "Avos Workshop": "AWO",
  "Bandit Camp Exit": "BCE",
  "Bandit Cave Lower": "BCL",
  "Bandit Cave Upper": "BCU",
  "Bandits Toll": "BTO",
  "Canyon Entrance Waterfall": "CEW",
  "Canyon Fortress": "CAF",
  "Canyon Lower South East": "CLS",
  "Canyon Mountain East": "CME",
  "Canyon Mountain South": "CMS",
  "Canyon Of The Lost": "COT",
  "Canyon Path North Mid": "CPNM",
  "Canyon Path North West": "CPNW",
  "Canyon Path South East": "CPSE",
  "Canyon Path South West": "CPSW",
  "Canyon Survivor": "CAS",
  "Canyon Upper North West": "CUN",
  "Canyon Valley South": "CVS",
  "Canyon Walk Way": "CWW",
  "Canyon Waterfall Mid North": "CWM",
  "Canyon Waterfall North": "CWN",
  "Chained House": "CHH",
  "Cherry Blossom Forest": "CBF",
  "Cinfras Entrance": "CIE",
  "Cinfras Thanos Transition": "CTT",
  "City of Troms": "COF",
  "Cliff Side of the Lost": "CSOT",
  "Cliffside Lake": "CLL",
  "Cliffside Passage": "CLP",
  "Cliffside Valley": "CLV",
  "Cliffside Waterfall": "CLW",
  "Corkus City South": "CCS",
  "Corkus Countryside": "CCO",
  "Corkus Forest South": "CFS",
  "Corkus Mountain": "COM",
  "Dark Forest Cinfras Transition": "DFC",
  "Dead Island North East": "DIN",
  "Dead Island North West": "DINW",
  "Dead Island South East": "DIS",
  "Dead Island South West": "DISW",
  "Dernel Jungle Lower": "DJL",
  "Dernel Jungle Mid": "DJM",
  "Dernel Jungle Upper": "DJU",
  "Desert East Lower": "DEL",
  "Desert East Mid": "DEM",
  "Desert East Upper": "DEU",
  "Desert Lower": "DLO",
  "Desert Mid-Lower": "DES",
  "Desert Mid-Upper": "DESE",
  "Desert Upper": "DUP",
  "Desert West Lower": "DWL",
  "Desert West Upper": "DWU",
  "Detlas Close Suburbs": "DCS",
  "Detlas Far Suburbs": "DFS",
  "Detlas Savannah Transition": "DST",
  "Detlas Trail East Plains": "DTE",
  "Detlas Trail West Plains": "DTW",
  "Durum Isles Center": "DIC",
  "Durum Isles East": "DIE",
  "Durum Isles Lower": "DIL",
  "Durum Isles Upper": "DIU",
  "Efilim East Plains": "EEP",
  "Efilim South East Plains": "ESE",
  "Efilim South Plains": "ESP",
  "Efilim Village": "EFV",
  "Elkurn Fields": "ELF",
  "Entrance to Rodoroc": "ETR",
  "Entrance to Thesead North": "ETTN",
  "Entrance to Thesead South": "ETTS",
  "Factory Entrance": "FAE",
  "Fortress North": "FON",
  "Fortress South": "FOS",
  "Gelibord Castle": "GEC",
  "Gelibord Corrupted Farm": "GCF",
  "Great Bridge Jungle": "GBJ",
  "Great Bridge Nesaak": "GBN",
  "Hive": "HIV",
  "Hive South": "HIS",
  "Hobbit River": "HOR",
  "Jungle Lake": "JUL",
  "Jungle Lower": "JLO",
  "Jungle Mid": "JUM",
  "Jungle Upper": "JUU",
  "Lava Lake": "LAL",
  "Lava Lake Bridge": "LLB",
  "Leadin Fortress": "LEF",
  "Light Forest Canyon": "LFC",
  "Light Forest East Lower": "LFE",
  "Light Forest East Mid": "LFEM",
  "Light Forest East Upper": "LFEU",
  "Light Forest North Entrance": "LFN",
  "Light Forest North Exit": "LFNE",
  "Light Forest South Entrance": "LFS",
  "Light Forest West Lower": "LFW",
  "Light Forest West Mid": "LFWM",
  "Light Forest West Upper": "LFWU",
  "Lighthouse Plateau": "LIP",
  "Llevigar Entrance": "LLE",
  "Llevigar Farm Plains East": "LFP",
  "Llevigar Farm Plains West": "LFPW",
  "Llevigar Gate East": "LGE",
  "Llevigar Gate West": "LGW",
  "Llevigar Plains East Lower": "LPE",
  "Llevigar Plains East Upper": "LPEU",
  "Llevigar Plains West Lower": "LPW",
  "Llevigar Plains West Upper": "LPWU",
  "Loamsprout Camp": "LCA",
  "Lone Farmstead": "LOF",
  "Maltic Plains": "MAP",
  "Mansion of Insanity": "MOI",
  "Mining Base Lower": "MBL",
  "Mining Base Upper": "MBU",
  "Molten Heights Portal": "MHP",
  "Mountain Edge": "MOE",
  "Mountain Path": "MOP",
  "Nemract Plains East": "NPE",
  "Nemract Plains West": "NPW",
  "Nemract Quarry": "NEQ",
  "Nemract Road": "NER",
  "Nemract Town": "NET",
  "Nesaak Bridge Transition": "NBT",
  "Nesaak Plains Lower North West": "NPL",
  "Nesaak Plains North East": "NPN",
  "Nesaak Plains South East": "NPS",
  "Nesaak Plains South West": "NPSW",
  "Nesaak Plains Upper North West": "NPU",
  "Nesaak Village": "NEV",
  "Nether Gate": "NEG",
  "Nether Plains Lower": "NEP",
  "Nether Plains Upper": "NETH",
  "Nivla Woods Edge": "NIW",
  "Nivla Woods Entrance": "NWO",
  "North Farmers Valley": "NFV",
  "North Nivla Woods": "NNW",
  "Path to Ahmsord Lower": "PTAL",
  "Path to Ahmsord Upper": "PTAU",
  "Path To Ozoth\u2019s Spire Lower": "PTO",
  "Path To Ozoth\u2019s Spire Mid": "PTOS",
  "Path To Ozoth\u2019s Spire Upper": "PAT",
  "Path To Thanos": "PATH",
  "Path To The Arch": "PTTA",
  "Phinas Farm": "PHF",
  "Pigmen Ravines Entrance": "PRE",
  "Plains": "PLA",
  "Plains Coast": "PLC",
  "Pre-Light Forest Transition": "PFT",
  "Quartz Mines North East": "QMN",
  "Quartz Mines North West": "QMNW",
  "Quartz Mines South East": "QMS",
  "Quartz Mines South West": "QMSW",
  "Ragni East Suburbs": "RES",
  "Ragni North Suburbs": "RNS",
  "Ragni Plains": "RAP",
  "Raider\u2019s Base Lower": "RBL",
  "Raider\u2019s Base Upper": "RBU",
  "Road To Light Forest": "RTL",
  "Road To Mine": "ROT",
  "Rymek East Lower": "REL",
  "Rymek East Mid": "REM",
  "Rymek East Upper": "REU",
  "Rymek West Lower": "RWL",
  "Rymek West Mid": "RWM",
  "Rymek West Upper": "RWU",
  "Sablestone Camp": "SAC",
  "Savannah East Lower": "SAE",
  "Savannah East Upper": "SEU",
  "Savannah West Lower": "SWL",
  "Savannah West Upper": "SWU",
  "Skiens Island": "SIS",
  "South Farmers Valley": "SFV",
  "South Nivla Woods": "SNW",
  "South Pigmen Ravines": "SPR",
  "Sunspark Camp": "SUC",
  "Swamp Dark Forest Transition Lower": "SDF",
  "Swamp Dark Forest Transition Mid": "SDFT",
  "Swamp Dark Forest Transition Upper": "SWD",
  "Swamp East Lower": "SWE",
  "Swamp East Mid": "SEM",
  "Swamp East Mid-Upper": "SEA",
  "Swamp East Upper": "SWA",
  "Swamp Lower": "SLO",
  "Swamp Mountain Base": "SMB",
  "Swamp Mountain Transition Lower": "SMT",
  "Swamp Mountain Transition Mid": "SMTM",
  "Swamp Mountain Transition Mid-Upper": "SWM",
  "Swamp Mountain Transition Upper": "SMTU",
  "Swamp Plains Basin": "SPB",
  "Swamp West Lower": "SWW",
  "Swamp West Mid": "SWAM",
  "Swamp West Mid-Upper": "SWM2",
  "Swamp West Upper": "SWU2",
  "Taproot Descent": "TAD",
  "Temple of the Lost East": "TOT",
  "Ternaves Plains Lower": "TPL",
  "Ternaves Plains Upper": "TPU",
  "Thanos Exit Upper": "TEU",
  "The Bear Zoo": "TBZ",
  "The Broken Road": "TBR",
  "The Silent Road": "TSR",
  "Valley of the Lost": "VOT",
  "Viscera Pits East": "VPE",
  "Volcanic Slope": "VOS",
  "Volcano Lower": "VOL",
  "Volcano Upper": "VOU",
  "Wizard Tower North": "WTN",

  // Old territory names found only in exchange data (not in old territories.json)
  "Aldorei Valley South Entrance": "AVS",
  "Aldorei's Arch": "ALA",
  "Cinfras County Lower": "CCL",
  "Cinfras County Mid-Lower": "CIC",
  "Cinfras County Mid-Upper": "CINF",
  "Cinfras County Upper": "CCU",
  "Corkus Docks": "COD",
  "Corkus Forest North": "CFN",
  "Corkus Sea Port": "CSP",
  "Corkus Statue": "COS",
  "Ghostly Path": "GHP",
  "Gylia Lake North East": "GLN",
  "Gylia Lake North West": "GLNW",
  "Gylia Lake South East": "GLS",
  "Gylia Lake South West": "GLSW",
  "Lexdales Prison": "LEP",
  "Light Forest Entrance": "LIF",
  "Light Forest South Exit": "LFSE",
  "Military Base": "MIB",
  "Military Base Lower": "MBA",
  "Military Base Upper": "MIL",
  "Nesaak Plains Mid North West": "NPM",
  "Old Crossroads North": "OCN",
  "Old Crossroads South": "OCS",
  "Path To Military Base": "PTM",
  "Thanos Valley West": "TVW",
  "Viscera Pits West": "VPW",

  // 2018-era territories (predating even the pre-Rekindled names).
  // These territories were renamed or removed before the Rekindled World
  // update.  They appear in the 2018-2021 Discord war-log import.
  // Location data is not yet available — they won't render on the map
  // until old_territories_verbose.json is added.
  "Abandoned Church": "ABCH",
  "Abandoned Tower": "ABTW",
  "Angry Village": "AGV",
  "Animal Bridge": "ANB",
  "Arachnida Cave": "ARCC",
  "Banshees Cave": "BNC",
  "Battle Tower": "BTT",
  "Black Camp": "BKC",
  "Black Magic": "BKM",
  "Bucie North East": "BNE",
  "Bucie North West": "BNW",
  "Bucie South East": "BCSE",
  "Bucie South West": "BCSW",
  "Corkus Abandoned Tower": "CKAT",
  "Corrupted Hand": "CRH",
  "Corrupted Impact": "CRI",
  "Corrupted Village": "CVG",
  "Farmers Valley": "FMV",
  "Graveyard North": "GYN",
  "Graveyard South": "GYS",
  "Gray Zone": "GRZ",
  "Green Camp": "GRNC",
  "Gromblins Hideout": "GMH",
  "Imperial Gate": "IMT",
  "Light Realm East": "LRE",
  "Light Realm East Mid-Upper": "LRMU",
  "Light Realm Entrance Upper": "LREN",
  "Light Realm Mushrooms": "LRM",
  "Mt. Wynn": "MTW",
  "Orphion\u2019s Seal": "OPS",
  "Orphion\u2019s Seal Upper": "OPSU",
  "Path To Prison": "PTPR",
  "Potato Laboratory": "PLB",
  "Qira\u2019s Battle Room": "QBR",
  "Red Camp": "RDC",
  "Sacrifice": "SACR",
  "Shanjugin\u2019s River": "SJR",
  "Spiraling Trees": "SPT",
  "Statue": "STT",
};

// Merge old names into the combined mapping so all lookups still work
Object.assign(TERRITORY_TO_ABBREV, OLD_TERRITORY_TO_ABBREV);

// Sets for fast era-filtering during snapshot reconstruction
export const OLD_TERRITORY_NAMES = new Set(Object.keys(OLD_TERRITORY_TO_ABBREV));
export const OLD_TERRITORY_ABBREVS = new Set(Object.values(OLD_TERRITORY_TO_ABBREV));

// Abbreviation → Full name mapping (reverse lookup)
export const ABBREV_TO_TERRITORY: Record<string, string> = Object.fromEntries(
  Object.entries(TERRITORY_TO_ABBREV).map(([name, abbrev]) => [abbrev, name])
);

// Normalized lookup: maps apostrophe-normalized names → abbreviations.
// Handles mismatches between Unicode right single quote (\u2019) and ASCII
// apostrophe (') in territory names from different data sources.
function normalizeApostrophes(name: string): string {
  return name.replace(/[\u2018\u2019\u2032\u00B4]/g, "'");
}

const NORMALIZED_LOOKUP: Record<string, string> = {};
for (const [name, abbrev] of Object.entries(TERRITORY_TO_ABBREV)) {
  NORMALIZED_LOOKUP[normalizeApostrophes(name)] = abbrev;
}

// Known typos/aliases in historical exchange data → canonical name.
// Maps 2018-era territory names and typos to their canonical equivalents
// in TERRITORY_TO_ABBREV / OLD_TERRITORY_TO_ABBREV.
const DB_NAME_ALIASES: Record<string, string> = {
  "Otherwordly Monolith": "Otherworldly Monolith",

  // Nivla Forest → Nivla Woods renames (happened pre-Rekindled)
  "Nivla Forest": "Nivla Woods",
  "Nivla Forest Edge": "Nivla Woods Edge",
  "Nivla Forest Entrance": "Nivla Woods Entrance",
  "Nivla Forest Exit": "Nivla Woods Exit",
  "North Nivla Forest": "North Nivla Woods",
  "South Nivla Forest": "South Nivla Woods",

  // Light Realm → Light Forest renames (happened pre-Rekindled)
  "Light Realm East Lower": "Light Forest East Lower",
  "Light Realm East Mid": "Light Forest East Mid",
  "Light Realm East Upper": "Light Forest East Upper",
  "Light Realm Entrance": "Light Forest South Entrance",
  "Light Realm Corruption": "Light Forest Canyon",

  // Road to Corruption → Road To Light Forest
  "Road to Corruption": "Road To Light Forest",

  // Dernal → Dernel spelling (2018-era)
  "Dernal Jungle Lower": "Dernel Jungle Lower",
  "Dernal Jungle Mid": "Dernel Jungle Mid",
  "Dernal Jungle Upper": "Dernel Jungle Upper",

  // Efelim → Efilim spelling (2018-era)
  "Efelim East Plains": "Efilim East Plains",
  "Efelim South East Plains": "Efilim South East Plains",
  "Efelim South Plains": "Efilim South Plains",
  "Efelim Village": "Efilim Village",
};

/**
 * Convert a full territory name to its abbreviation.
 * Handles apostrophe normalization and known typos in DB data.
 */
export function toAbbrev(territoryName: string): string {
  return TERRITORY_TO_ABBREV[territoryName]
    ?? NORMALIZED_LOOKUP[normalizeApostrophes(territoryName)]
    ?? TERRITORY_TO_ABBREV[DB_NAME_ALIASES[territoryName] ?? ""]
    ?? territoryName;
}

/**
 * Convert an abbreviation back to the full territory name
 */
export function fromAbbrev(abbrev: string): string {
  return ABBREV_TO_TERRITORY[abbrev] || abbrev;
}

/**
 * Check if a string is a known territory name
 */
export function isKnownTerritory(name: string): boolean {
  return name in TERRITORY_TO_ABBREV
    || normalizeApostrophes(name) in NORMALIZED_LOOKUP
    || (DB_NAME_ALIASES[name] ?? "") in TERRITORY_TO_ABBREV;
}

/**
 * Check if a string is a known abbreviation
 */
export function isKnownAbbrev(abbrev: string): boolean {
  return abbrev in ABBREV_TO_TERRITORY;
}
