CREATE TABLE IF NOT EXISTS kick_list (
  uuid VARCHAR(36) PRIMARY KEY,
  ign VARCHAR(64) NOT NULL,
  tier INTEGER NOT NULL CHECK (tier IN (1, 2, 3)),
  added_by VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
